from typing import Any, Dict
import re
from dotenv import load_dotenv

from langchain.agents import create_agent
from langchain.messages import AIMessageChunk, HumanMessage
from langchain.tools import tool
from langchain_ollama import ChatOllama
from langgraph.checkpoint.memory import InMemorySaver
from tavily import TavilyClient

# 1. Environment & Tools
load_dotenv()
tavily_client = TavilyClient()

@tool
def web_search(query: str) -> str:
    """Search the web for recipe and cooking information."""
    results = tavily_client.search(query, max_results=2, search_depth="basic")
    
    clean_snippets = []
    for res in results.get("results", []):
        content = res.get("content", "")
        content = re.sub(r"\[.*?\]", "", content)
        clean_snippets.append(content.strip())
        
    # Return concise body text only to keep the prompt context lean
    return " ".join(clean_snippets)[:800]

# 2. System Instructions
system_prompt = """
You are a rapid-fire personal chef assistant.

Your job is to give quick, ultra-scannable meal ideas around 150-200 words.

Formatting rules:
1. When receiving greetings or general queries, reply briefly and conversationally.
2. When ingredients are provided, give ONE recipe idea with:
   - **Dish Name** (bold) + Total Time
   - **Key Ingredients** (comma-separated list, not a vertical checklist)
   - **Quick Method** (maximum 3 concise bullet points)
3. NEVER display raw search results, website names, links, or image captions. Keep it bite-sized.
"""

# 3. Model Configuration
llm = ChatOllama(
    model="qwen3:8b",
    temperature=0.2,
    num_ctx=4096,
)

# 4. Memory & Agent Setup
memory = InMemorySaver()

agent = create_agent(
    model=llm,
    tools=[web_search],
    system_prompt=system_prompt,
    checkpointer=memory,
)

# 5. Interactive Chat Session
thread_config = {"configurable": {"thread_id": "session-1"}}

print("Chef Bot ready! Type 'exit' or 'quit' to stop.\n")

while True:
    user_input = input("You: ").strip()
    if not user_input:
        continue
    if user_input.lower() in ["exit", "quit"]:
        print("Goodbye!")
        break

    print("\nChef: ", end="", flush=True)
    
    # Stream tokens
    for chunk, metadata in agent.stream(
        {"messages": [HumanMessage(content=user_input)]},
        thread_config,
        stream_mode="messages",
    ):
        # Print only text tokens generated by the assistant, ignoring tool call JSON chunks
        if isinstance(chunk, AIMessageChunk) and chunk.content:
            # Check if this chunk is part of tool calling arguments
            has_tool_call = bool(getattr(chunk, "tool_call_chunks", None))
            if not has_tool_call:
                print(chunk.content, end="", flush=True)

    print("\n")